name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Alterar se o branch principal for "master"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Pode ajustar conforme necessário

      - name: Instalar dependências
        run: npm install

      - name: Criar build do Vite
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
